# ~/.config/starship.toml

command_timeout = 9999999999

[character]
#use_symbol_for_status = true

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted = "!"
untracked = "ğŸ¤· Ã—${count}"
stashed = "ğŸ’°"
modified = "ğŸ“ Ã—${count}"
staged = '[++\($count\)](green)'
deleted = "ğŸ—‘ï¸  Ã—${count}"

[golang]
symbol = "go "

[package]
disabled = true
[nodejs]
disabled = true
[aws]
disabled = true
